(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "dash")
(depends-on "enh-ruby-mode")
(depends-on "epl")
(depends-on "f")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")
(depends-on "web-mode")
